### ISSUE TITLE
GNB ->  Home | Hachery | Team | Github

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/team-durumi.github.io#7]
```
gnb:
- name: Homepage(github.pages)
  url: https://durumi.io
  weight: -120
- name: Hatchery
  url: https://hatchery.durumi.io
  weight: -110
- name: Shops(team)
  url: https://shops.durumi.io
  weight: -100
- name: Github
  url: https://github.com/team-durumi
  weight: -90
```

![스크린샷 2022-03-07 오후 12 10 31](https://user-images.githubusercontent.com/6022883/156961697-14ddce4e-6cb7-4025-a15a-1d5374591dd1.png)

## 마케팅 테마
- layout -> asset/components 옮겨보고, 테스트도 좀 하고 있는데요. 지나번 얘기 나왔던 데로 GNB를 붙여보려 합니다. 
- 처음에는 Hatchery가 없겠지만, 고객 대응 github 연결된 Hugo app 혹은 Roll 0.1 버전을 붙여보면 어떨까 해요.
- Shops는 처음에는 후드 팔자 이런생각으로 만들다가, 좀 생각해 보니 Team에 합류하는 on-boarding 같은 과정이 여기 들어가도 괜찮을 것 같아 보이더라구요. 
--  몇 개 영상을 시청하고, 팀이 괜찮거나 합류할 생각이 있다면, 후드 사시고, 업무 협력도 하고 (Roll로 아카이브를 만들거나, 관리하는 사람도 이쪽으로 몰면 어떨까, 개발 안 하면 후드라도 좀 사지 그래 ?)
